version: "3"

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./src/data:/usr/share/nginx/data
      - ./src/your-domain.etc/www:/usr/share/nginx/your-domain.etc/www
    ports:
      - "8080:80"
    restart: always
